[package]
name = "neon"
version = "0.10.0"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "A safe abstraction layer for Node.js."
readme = "README.md"
homepage = "https://www.neon-bindings.com"
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
exclude = ["neon.jpg", "doc/**/*"]
edition = "2018"

[dev-dependencies]
nodejs-sys = "0.13.0"
semver = "0.9"
psd = "0.1.9"     # used for a doc example
failure = "0.1.5" # used for a doc example

[dependencies]
libloading = "0.7.3"
semver = "0.9.0"
smallvec = "1.4.2"
neon-macros = { version = "=0.10.0", path = "crates/neon-macros" }

[features]
default = ["napi-1"]

# Default N-API version. Prefer to select a minimum required version.
# DEPRECATED: This is an alias that should be removed
napi-runtime = ["napi-6"]

# Select the N-API version
# Feature flags to enable the experimental N-API runtime. For now, this feature
# is disabled by default.
# The Node N-API documentation specifies N-API and Node version requirements
# https://nodejs.org/api/n-api.html
napi-1 = []
napi-2 = ["napi-1"]
napi-3 = ["napi-2"]
napi-4 = ["napi-3"]
napi-5 = ["napi-4"]
napi-6 = ["napi-5"]
napi-latest = ["napi-6"]
napi-experimental = ["napi-6"]

# DEPRECATED: These perform no action and will be removed in 1.0
try-catch-api = []
channel-api = []
event-queue-api = []
promise-api = []
task-api = []

# Feature flag to include procedural macros
# DEPRECATED: This is always enabled and should be removed.
proc-macros = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
features = [
    "napi-experimental",
]

[workspace]
members = [
    "crates/neon-macros",
    "test/electron",
    "test/napi"
]
