[alias]
# Neon defines mutually exclusive feature flags which prevents using `cargo clippy --all-features`
# The following aliases simplify linting the entire workspace
neon-check = " check  --all --all-targets --features napi-experimental"
neon-clippy = "clippy --all --all-targets --features napi-experimental -- -A clippy::missing_safety_doc"
neon-test = "  test   --all               --features=napi-experimental"
neon-doc = "   rustdoc -p neon            --features=napi-experimental -- --cfg docsrs"
